org: '1256505457'
app: time-lover-server
stage: prod
component: koa
name: koa-5k9c_ZBVu
inputs:
  src:
    src: ./
    exclude:
      - .env
      - docs
      - build
      - _tests_
      - .github
      - src
      - .eslintrc.json
      - jest.config.ts
  region: ap-chengdu
  runtime: Nodejs10.15
  apigatewayConf:
    protocols:
      - http
      - https
    environment: release
    serviceTimeout: 60
    autoCreateDns: false
  isAutoCiDeploy: false
  functionConf:
    eip: false
    timeout: 10
    memorySize: 256
    environment:
      variables:
        NODE_ENV: production
  layers:
    - name: '${output:${stage}:${app}:time-lover-server-layer.name}'
      version: '${output:${stage}:${app}:time-lover-server-layer.version}'
